sprint-5/step-1
maslomeister/react-burger pull request #7
Opened 2022-05-30 20:09 UTC by maslomeister

2022-05-31 01:08 UTC, grishbar requested changes
Проделана прекрасная работа, приложение выглядит великолепно, весь запрашиваемый функционал реализован идеально. Взаимодействие с веб сокетам сделал абсолютно верно 👍 . Есть несколько недочетов, которые надо бы поправить до принятия работы:

- [ ] Убрать _ из названия переменных, которые будут использоваться
- [ ] Доставать объекты из хранилища при помощи деструктуризации
- [ ] Вынести большие/сложно вычисляемые объекты из useEffect в useMemo
- [ ] Избавиться от дублирования типов в компонентах
- [ ] Избавить от дублирования кода

2022-05-31 01:08 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
>    const _removeBun = useCallback(() => {
`надо исправить` 
надо бы переименовать как нибудь эту переменную, так как с нижним подчеркиванием принято называть переменные, которые не используются, даже линтер их перестает подсвечивать если они не используются

2022-05-31 01:08 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
>    }, []);
`можно лучше` 
можешь либо добавить dispatch в зависимости либо игнорировать warning, так как лишние перерендеры вызываться не будут так как хук возвращающий dispatch будет возвращать всегда один и тот же экземпляр объекта, а ворнинг не крашит приложение. Просто такая длинная строчка в коде добавляет лишнюю смысловую нагрузку

2022-05-31 01:08 UTC, grishbar commented on src/components/ingredient-circle-image/ingredient-circle-image.tsx
> +      )}
`надо исправить` 
тут у тебя дублирование кода, надо бы переписать и избавиться от тернарника он не нужен, старайся всегда по возможности писать колд не использую тернарный оператор, так как он читается в разы сложней чем обычное условие, потому что создает очень большой контекст кода который ты одновременно читаешь

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +import { useAppSelector, useAppDispatch } from "../../services/hooks";
`отлично` 
прикольное решение для типизация стора который возвращается при диспатче, очень удобные хуки получились 👍

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +  const orderData = useAppSelector((state) => state.orderDetails.orderData);
`надо исправить` 
доставая объекты из хранилища старайся действовать тому же принципу как ты получаешь пропсы в компоненте, все пропсы ты получаешь при помощу деструктурирования, тем самым давая себе возможность в будущем безопасно мутировать объект, не боясь, что ты сломаешь приложение, или где то неожиданно смутируешь данные и они поменяются в другом месте

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +  const [ingredients, setIngredients] = useState<IOrderedIngredient[]>();
`надо исправить` 
кажется тут по дэфолту должен быть пустой массив а не undefined, так намного удобней взаимодействовать с объектом ингредиентов, так как тогда не придется проверять, что у тебя там что то лежит прежде чем использовать методы массива + всегда старайся придерживаться правила, что чем уже тип у объекта тем лучше, сейчас у тебя тип `IOrderedIngredient[] | undefined` а если по initial значение поставишь как пустой массив, то сузишь тип до `IOrderedIngredient[]`

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +  const _ingredients = useAppSelector(
`надо исправить` 
пройдись пожалйста по всему проекту и везде избавься от нижнего подчеркивания в названии переменных, которые ты будешь использовать

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +    });
`надо исправить` 
сейчас у тебя на каждый перерендер будет пересчиитываться эта большая переменная, это не ок. Вынеси пожалуйста эту переменную из useEffect и оберни ее в [useMemo](https://ru.reactjs.org/docs/hooks-reference.html#usememo), так твое приложение сразу станет напорядок оптимизированней

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +    }, 0);
`надо исправить` 
это тоже нужно считать отдельно в useMemo

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +      {orderData && ingredients ? (
`надо исправить` 
такой тернарник прочитать супер сложно, тебе одновременно надо смотреть на 55 строк, можно сделать намного проще и доступней для чтения:
```
if (!orderData || !ingredients) {
   return   (
      <LoadingScreen text="Загружаются данные заказа" size="medium" />
   );
}

return (
   ...
)
```

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +              : "Создан"}
`надо исправить` 
в jsx должно быть по миниму логики, вся логика должна быть в компоненте, а в jsx в идеале только условия, для условного рендера и маппинг по массивам. Так что вынеси пожалйста логику что писать в статусе в компонент, также двойной тернарник это известный антипаттерн, его прочитать невозможно, представь как он должен читаться - (если условие правдиво то одно, если нет то если другое условие верно то второе значение а если неверно первое и неверно второе то третье значение) осознание в каких случаях у тебя будет третье значени занимает невероятное количество времени. Так, что воспользуйся тут конструкцией [switch case](https://learn.javascript.ru/switch) пожалуйста

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +            })}
`можно лучше` 
это большой довольно независимый блок кода, можешь вынести его в компонент и обернуть useMemo, чтобы не перерисовывать его постоянно и так читаться будет намного проще

2022-05-31 01:08 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +                      double={ingredient.type === "bun" ? true : undefined}
`можно лучше` 
меньше тернарников = лучше код
```
double={ingredient.type === "bun" || undefined}
```

2022-05-31 01:08 UTC, grishbar commented on src/components/order/order.module.css
> +}
`можно лучше` 
тут мы учим не верстку, так, что ок, но в действительно согласно [документации разработчиков Бэма](https://ru.bem.info/methodology/css/#Комбинированные-селекторы), ты не должен использовать комбинаторы, а для каждого уникального стиля должен быть свой класс/модификатор
Во первых если кто то решит передвинуть элементы в jsx он не полезет в стили проверять писал ли там кто комбинаторы или нет, соответственно все сломается, во вторых код с комбинаторами совсем не масштабируем, добавление/удаление элементов в компоненте начинает стоить намного дороже

2022-05-31 01:08 UTC, grishbar commented on src/components/order/order.tsx
> +}
`надо исправить` 
ты дублируешь типы, общие типы должны быть вынесены в отдельную папку и переиспользоваться

2022-05-31 01:08 UTC, grishbar commented on src/components/order/order.tsx
> +
`надо исправить` 
точно такую же логику ты уже писал в одном месте, кажется отличная место для выноса этого блока в  функцию в утилиты и начать использовать ее, чтобы не дублировать код

2022-05-31 01:08 UTC, grishbar commented on src/components/order/order.tsx
> +  }, [dispatch, location, navigate]);
`надо исправить` 
не очень понял, почему тут не стал указывать все зависимости которые нужны, убери пожалуйста отключение eslint тут и пропиши все зависимости. Если это было чем то обусловленно, то отпиши об этом пожалуйста

2022-05-31 01:08 UTC, grishbar commented on src/components/order/order.tsx
> +              })}
`надо исправить` 
тут также слишком много логики получилось, вынеси ее в компонент, пожалуйста, а еще лучше в отдельный компонент, так как чем меньше у тебя компоненты и чем более разделен твой код на атомарные функции, тем проще его читать. Также для маленьких функций легко описать [JSDOC](https://jsdoc.app/about-getting-started.html), что в гугловском линтере обязательно делать

2022-05-31 01:08 UTC, grishbar commented on src/pages/order-info-page/order-info-page.tsx
> +  }, [_ingredients, orderData, orderData?.ingredients]);
`надо исправить` 
не забудь пройтись по всем компонентов и везде избавиться от дублирования кода

2022-05-31 01:08 UTC, grishbar commented on src/pages/orders/orders.tsx
> +  }, [dispatch]);
`отлично` 
Круто, что не забыл отключить вебсокет при размонтировании компонента

2022-05-31 01:08 UTC, grishbar commented on src/pages/profile-orders/profile-orders.tsx
> +    }
`надо исправить` 
Когда тебе нужно вызвать несколько dispatch рядом, вероятней всего более правильным решением будет вынести это дело в экшен, потому что во первых скорей всего будут еще места где тебе захочется сделать такую же логику, а значит придется снова использовать несколько dispatch. А во вторых зачастую ты этими несколькими dispatchами пытаешься выполнить одну задачу, а значит они должны быть в отдельной понятной функции

2022-05-31 12:17 UTC, maslomeister commented on src/pages/profile-orders/profile-orders.tsx
> +    }
Привет, можешь подсказать, у меня вся логика токенов поломанная получилось, отсюда и двойные диспатчи, как лучше реализовать обновление токена? Сейчас логика следующая:
При маунте  app проверяем есть ли в куки токены, если есть оба, то все хорошо, если есть только refresh, используя его диспатчим экшен с получением access, внутри него кладем в куки токены, для access делаем expires и уже в отдельных защищенных роутах где нужен токен в маунте проверю токен из кэша и если вдруг что опять же беру новый, по идее это такое себе и нужно как-то по-другому реализовать, но я что-то не соображу как

2022-06-01 12:59 UTC, grishbar requested changes
Отлично проект стал намного лучше, осталось еще чуть-чуть до принятия работы:

- [ ] Избавиться от дублирования кода
- [ ] Семантически правильно использовать useMemo и useEffect

2022-06-01 12:59 UTC, grishbar commented on src/components/app/app.tsx
> +                  </ProtectedRouteGuest>
`можно лучше` 
пропсы которые не укладываются в одну строчку лучше выносить в компонент, так куда проще читается

2022-06-01 12:59 UTC, grishbar commented on src/components/ingredient-circle-image/ingredient-circle-image.tsx
> +  }
`можно лучше` 
проще будет если overlay всегда одна и та же переменная, а в верстку условно его отрисовываешь или можешь так написать:
const overlay = amount && (<>...</>);

2022-06-01 12:59 UTC, grishbar commented on src/components/order-details/order-details.tsx
> +  if (status === "getOrderNumber/loading") {
`можно лучше` 
старые значения статуса (loading, succeded) мне нравились больше)

2022-06-01 12:59 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +  }, [allIngredients, orderData]);
`надо исправить` 
[useMemo](https://ru.reactjs.org/docs/hooks-reference.html#usememo) надо использовать чтобы пересчитывать какой то объект и хранить его состояние, то есть:
const memoizedValue = useMemo(() => computeExpensiveValue(a, b), [a, b]);
а тут ты хочешь вызывать какие то sideEffectы которые обновляют состояние, компонента это должно быть в  хуке useEffect, или можешь переписать на хранение этих данных в переменной которая высчитывается через useMemo

2022-06-01 12:59 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +  }, [ingredients]);
`надо исправить` 
тут аналогично предыдущему комментарию, side эффекты должны вызываться в useEffect

2022-06-01 12:59 UTC, grishbar commented on src/components/order-info-modal/order-info-modal.tsx
> +  };
`отлично` 
🔥 огонь, теперь компонент читать куда проще
можно еще ruStatus посчитать через useMemo, тогда не придется его вызывать в jsx

2022-06-01 12:59 UTC, grishbar commented on src/components/order/order.tsx
> +
`надо исправить` 
пройдись пожалуйста по всему проекту и исправь везде неправильно используемые useMemo и useEffect

2022-06-01 12:59 UTC, grishbar commented on src/components/protected-routes/protected-routes-user.tsx
> +  const location = useLocation() as TLocationProps;
`надо исправить` 
[хук useLocation принимает дженерики ](https://stackoverflow.com/questions/61668623/react-typescript-correct-type-for-uselocation-from-react-router-dom) , так что надо переделать и передать нужный тип в дженерик. Каждый раз когда ты используешь as или any или  @ts-ignore это значит, что ты делаешь что то не так, и создаешь пространство для появления багов в будущем, так, что старайся этого избегать. В данном случае конечно это не критично, но старайся использовать как правило не использовать as без смертельной необходимости

2022-06-01 12:59 UTC, grishbar commented on src/components/protected-routes/protected-routes-user.tsx
> +        to={location.state ? location.state.from : "/"}
`можно лучше` 
location?.state?.from ?? "/"

2022-06-01 12:59 UTC, grishbar commented on src/pages/order-info-page/order-info-page.tsx
> +  const ruStatus = () => {
`надо исправить` 
дублируешь логику из order-info-modal, надо вынести общую часть в отдельный компонент, и переиспользовать

2022-06-01 12:59 UTC, grishbar commented on src/pages/orders/orders.module.css
> +  grid-template-rows: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;
`можно лучше` 
чтобыы не дублировать много колонок можно воспользоваться css функцией repeat - 
https://developer.mozilla.org/en-US/docs/Web/CSS/repeat

2022-06-01 12:59 UTC, grishbar commented on src/pages/orders/orders.tsx
> +            })}
`можно лучше` 
лучше снаружи через useMemo создать объект который будет содержать элементы по которым нужно помапиться, тогда верстка будет намного короче и проще читаемей и перерендеры будут вызывтаься не так часто

2022-06-01 12:59 UTC, grishbar commented on src/pages/orders/orders.tsx
> +  } else {
`можно лучше` 
можно хранить три состояния: isLoading, isError, isFinished
и так как каждое из этих состояний взаимоисключает все остальные то писать:
```
if (isLoading) {
content = ...
}
if (isError) {
content = ...
}
if (isFinished) {
content = ...
}
...
```
и еще тут можешь создать HOC:
```
export function OrdersContainer({children}) {
    <motion.div
      key="feed"
      initial={{ x: motionInitialX }}
      animate={{ x: "0" }}
      transition={{
        type: "ease",
      }}
      className={styles["container"]}
    >
      {children}
    </motion.div>
}
```

2022-06-01 12:59 UTC, grishbar commented on src/services/reducers/order-details.ts
> +    const accessToken = getCookie("accessToken");
`можно лучше` 
надо бы подумать, что делать если accessToken не будет мне кажется, что будет хорошо если получение токена у тебя  будет в отдельном экшене, если его нет, то смотрим и обновляем при помощи рефреш токена, если и его нет, то редиректим на страницу авторизации и сохраняем в url страницу куда редиректить обратно. В теории это излишнее действие так как ты намного заранее проверяешь авторизирован пользователь или нет, но в продакшен приложении я бы обезопасился в этом месте тоже и создал бы подобный универсальный экшен

2022-06-01 12:59 UTC, grishbar commented on src/utils/helpers.ts
> +  }, 0);
`можно лучше` 
```
  return ingredients.reduce((acc, obj) => {
      return acc + ((obj.type === "bun") ? obj.price * 2 : obj.price);
  }, 0);
```

2022-06-02 12:39 UTC, maslomeister commented on src/components/protected-routes/protected-routes-user.tsx
> +  const location = useLocation() as TLocationProps;
https://github.com/remix-run/react-router/pull/7326#issuecomment-827862795 https://github.com/reach/router/issues/414#issuecomment-1111024170 
В react router v6 изменили useLocation и теперь он не принимает generic, поэтому тут такой код

2022-06-02 20:38 UTC, grishbar approved these changes
Прекрасно теперь работа стала прям совсем великолепной, оставил еще несколько комментариев, которые помогут сделать работу еще лучше. А так работу принимаю, удачи в дальнейшем обучении)

2022-06-02 20:38 UTC, grishbar commented on src/utils/utils.ts
> +}
`отлично` 
функция классная получилась, но истек токен или нет за это должен отвечать бэк, так более безопасно. В целом проверка и на фронте и на бэке истек токен или нет норм, но если критерии истекшего токена поменяются, то код придется менять в двух местах, а это не очень, всегда чем меньше источников данных, тем лучше

2022-06-02 20:38 UTC, grishbar commented on src/components/app/app.tsx
> +    status === "getUserData/loading" ||
`надо исправить` 
почему статус из state.burgerIngredients.status может содержать состояние загрузки данных пользователя?
Кажется это не совсем правильный подход к хранению данных, давай тут  state.authUser хранить статус загрузки аутентификационных данных

2022-06-02 20:38 UTC, grishbar commented on src/components/order/order.tsx
> +      })
`можно лучше` 
если имя переменной идентично свойству объекта, то можно не дублировать свойство: переменная а писать просто переменая, то есть:
```
      addDataToModal({
        createdAt,
        ingredients,
        name,
        number,
        status,
        updatedAt,
        _id,
      })
```
Также ты сам тут можешь заметить, что получился не очень приятно читаемый useCallback, можно передавать в компонент весь этот объект уже созданный а тут просто из него деструктурируешь нужные тебе пропсы, так получится куда проще и читаемей

2022-06-02 20:38 UTC, grishbar commented on src/pages/auth-pages/profile.tsx
> +        email: values.email!,
`надо исправить` 
в идеале в твоем коде не должно быть таких конструкций с восклицательным знаком, так как ты теряешь всю пользю typescript он больше не подсветит в этом месте, когда начнешь передавать что то не то. Попробуй корректно настроить типы, или написать typeGuard чтобы не приходилось использовать такую конструкцию

2022-06-02 20:38 UTC, grishbar commented on src/pages/order-info-page/order-info-page.tsx
> +
`можно лучше` 
много где используешь такую конструкцию, что если есть какая то переменная, то отрисуй контент, если нет, то отрисуй лоадер, логично вынести такое в HOC и пользоваться им чтобы не приходилось постоянно дублировать эту логику

2022-06-02 20:38 UTC, grishbar commented on src/pages/orders/orders.tsx
> +        />
`можно лучше` 
вот здесь просто передавай сразу весь объект также намного проще, + если в нем добавятся новые свойства не придется везде допрокидывать эти пропсы менять типы, которые принимает твой компонет и так далее

2022-06-02 21:45 UTC, merged